export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET';

export const ORDERS_REQUEST = 'ORDERS_REQUEST';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_FAIL = 'ORDERS_FAIL';

export const ORDER_COMPLETED_REQUEST = 'ORDER_COMPLETED_REQUEST';
export const ORDER_COMPLETED_SUCCESS = 'ORDER_COMPLETED_SUCCESS';
export const ORDER_COMPLETED_FAIL = 'ORDER_COMPLETED_FAIL';